data:extend(
{
  {
    type="item",
    name="atomic-plate",
    icon="__Extended-Factorio__/graphics/items/atomic-plate.png",
    icon_size=32,
    subgroup="extfac-plate",
    order="e-b",
    stack_size=50
  }
}
)
