data:extend(
{
  {
    type="item",
    name="enriched-plate",
    icon="__Extended-Factorio__/graphics/items/enriched-plate.png",
    icon_size=32,
    subgroup="extfac-plate",
    order="e-b",
    stack_size=200
  }
}
)
