data:extend(
{
  {
    type="item",
    name="reinforced-plate",
    icon="__Extended-Factorio__/graphics/items/reinforced-plate.png",
    icon_size=32,
    subgroup="extfac-plate",
    order="e-b",
    stack_size=100
  }
}
)
